WITH VALUE as(
SELECT
    B.AUTHOR_ID,
    B.CATEGORY,
    SUM(B.PRICE*BS.SALES) as TOTAL_SALES
FROM
    BOOK as B
JOIN
    BOOK_SALES as BS
ON
    B.BOOK_ID = BS.BOOK_ID
WHERE
    BS.SALES_DATE LIKE "2022-01%"
GROUP BY
    B.AUTHOR_ID, B.CATEGORY
    )
    
    
SELECT
    AUTHOR.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    VALUE.CATEGORY,
    VALUE.TOTAL_SALES
FROM
    VALUE
JOIN
    AUTHOR
ON
    VALUE.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY
    AUTHOR.AUTHOR_ID, VALUE.CATEGORY DESC