SELECT 
    II.ITEM_ID,
    II.ITEM_NAME,
    II.RARITY
FROM
    ITEM_INFO as II
LEFT OUTER JOIN
    ITEM_TREE as IT
ON
    II.ITEM_ID=IT.PARENT_ITEM_ID
WHERE
    IT.ITEM_ID is NULL
ORDER BY
    II.ITEM_ID DESC