SELECT
    P.PRODUCT_CODE,
    SUM(P.PRICE * OS.SALES_AMOUNT) as SALES
FROM
    PRODUCT as P
JOIN   
    OFFLINE_SALE as OS
ON
    P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY
    P.PRODUCT_CODE
ORDER BY
    SALES DESC, P.PRODUCT_CODE