WITH VALUE as (SELECT
    AI.ANIMAL_ID,
    DATEDIFF(AO.DATETIME,AI.DATETIME) as DATETIME,
    AI.NAME
FROM
    ANIMAL_INS as AI
JOIN
    ANIMAL_OUTS as AO
ON
    AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY
    DATETIME DESC)

SELECT
    VALUE.ANIMAL_ID,
    VALUE.NAME
FROM
    VALUE
LIMIt 2