# 테이블에서 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중
# 모두 30일 이상 대여 하려고 함
# 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 대여 불가능한 차량 식별
WITH UNAVAILABLE_CARS AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
),
-- 대여 가능한 차량 및 요금 계산
AVAILABLE_CARS AS (
    SELECT 
        C.CAR_ID,
        C.CAR_TYPE,
        ROUND(C.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) AS FEE
    FROM 
        CAR_RENTAL_COMPANY_CAR C
    JOIN 
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
    WHERE 
        C.CAR_TYPE IN ('세단', 'SUV')
        AND D.DURATION_TYPE = '30일 이상'
        AND C.CAR_ID NOT IN (SELECT CAR_ID FROM UNAVAILABLE_CARS)
)

SELECT 
    CAR_ID,
    CAR_TYPE,
    FEE
FROM 
    AVAILABLE_CARS
WHERE 
    FEE BETWEEN 500000 AND 2000000
ORDER BY 
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;