SELECT
    YEAR(OS.SALES_DATE) as YEAR,
    MONTH(OS.SALES_DATE) as MONTH,
    UI.GENDER,
    COUNT(DISTINCT UI.USER_ID) as USERS
FROM
    USER_INFO as UI
JOIN
    ONLINE_SALE as OS
ON
    UI.USER_ID =OS.USER_ID
WHERE
    UI.GENDER IS NOT NULL
GROUP BY
    YEAR(OS.SALES_DATE),MONTH(OS.SALES_DATE),UI.GENDER
