SELECT 
    ID,EMAIL,FIRST_NAME,LAST_NAME
FROM
    DEVELOPERS,SKILLCODES
WHERE
    1=1
    and SKILLCODES.CODE & DEVELOPERS.SKILL_CODE >0
    and SKILLCODES.CATEGORY = 'Front End'
GROUP BY ID,EMAIL,FIRST_NAME,LAST_NAME
ORDER BY
    ID