# 테이블에서 리뷰를 가장 많이 작성한
# 회원의 리뷰들을 조회
# 회원 이름, 리뷰 텍스트, 리뷰 작성일 출력
# 결과는 리뷰 작성일 기준으로 오름차순, 같다면 리뷰텍스트를 기준으로 오름 차순

WITH VALUE as (SELECT
    COUNT(*) as REVIEW_COUNT,
    MEMBER_ID
FROM
    REST_REVIEW
GROUP BY
    MEMBER_ID
ORDER BY REVIEW_COUNT DESC)

,COUNT_TABLE as (SELECT 
    MAX(value.REVIEW_COUNT) as MAX_COUNT
FROM
    value
)
, A as(SELECT 
    VALUE.REVIEW_COUNT,
       VALUE.MEMBER_ID
FROM
    COUNT_TABLE
JOIN
    VALUE
ON
    COUNT_TABLE.MAX_COUNT = VALUE.REVIEW_COUNT

)

,B as(SELECT
    A.MEMBER_ID,
    REST_REVIEW.REVIEW_TEXT,
    REST_REVIEW.REVIEW_DATE
FROM
    A
JOIN
    REST_REVIEW
ON
    A.MEMBER_ID = REST_REVIEW.MEMBER_ID
    )
    
SELECT
    MEMBER_PROFILE.MEMBER_NAME,
    B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE,"%Y-%m-%d") as REVIEW_DATE
FROM
    B
JOIN
    MEMBER_PROFILE
ON
    B.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
ORDER BY
    REVIEW_DATE ASC , REVIEW_TEXT ASC