SELECT
    c.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR as C
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
ON
    C.CAR_ID = RH.CAR_ID
WHERE
    C.CAR_TYPE LIKE "세단"
    and MONTH(RH.START_DATE) = 10
GROUP BY
    c.CAR_ID
ORDER BY
    c.CAR_ID DESC
