WITH VALUE AS (SELECT 
    CATEGORY,
    MAX(PRICE) as MAX_PRICE
FROM
    FOOD_PRODUCT
WHERE
    CATEGORY = "과자"
    or CATEGORY = "국"
    or CATEGORY = "김치"
    or CATEGORY = "식용유"
GROUP BY
    CATEGORY
ORDER BY
    PRICE DESC)
    
SELECT 
    VALUE.CATEGORY,
    VALUE.MAX_PRICE,
    FP.PRODUCT_NAME

FROM
    VALUE
JOIN
    FOOD_PRODUCT as FP
ON
    VALUE.CATEGORY = FP.CATEGORY
WHERE
    VALUE.MAX_PRICE = FP.PRICE
ORDER BY
    MAX_PRICE DESC